apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer
  labels:
    starship.io/name: starship-e2e-tests
    app.kubernetes.io/version: 4.0.0-alpha.1
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: explorer
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/name: explorer
data:
  osmosis-1.json: >-
    {"chain_name":"osmosis-1","coingecko":"osmosis","api":"http://localhost:1313","rpc":["http://localhost:26653"],"snapshot_provider":"","sdk_version":"0.45.6","coin_type":118,"min_tx_fee":"3000","addr_prefix":"osmo","logo":"","assets":[{"base":"uosmo","symbol":"OSMO","exponent":"6","coingecko_id":"osmosis-1","logo":""}]}
  cosmoshub-4.json: >-
    {"chain_name":"cosmoshub-4","coingecko":"cosmoshub","api":"http://localhost:1317","rpc":["http://localhost:26657"],"snapshot_provider":"","sdk_version":"0.45.6","coin_type":118,"min_tx_fee":"3000","addr_prefix":"cosmos","logo":"","assets":[{"base":"uatom","symbol":"COSMOS","exponent":"6","coingecko_id":"cosmoshub-4","logo":""}]}
